package cn.benevolence.patient.model;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.pdname
     *
     * @mbg.generated
     */
    private String pdname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.ppassword
     *
     * @mbg.generated
     */
    private String ppassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.psex
     *
     * @mbg.generated
     */
    private Integer psex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.page
     *
     * @mbg.generated
     */
    private Integer page;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.paddress
     *
     * @mbg.generated
     */
    private String paddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.pphone
     *
     * @mbg.generated
     */
    private String pphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.pmoney
     *
     * @mbg.generated
     */
    private String pmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.isdel
     *
     * @mbg.generated
     */
    private Integer isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.pid
     *
     * @return the value of patient.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.pid
     *
     * @param pid the value for patient.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.pname
     *
     * @return the value of patient.pname
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.pname
     *
     * @param pname the value for patient.pname
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.pdname
     *
     * @return the value of patient.pdname
     *
     * @mbg.generated
     */
    public String getPdname() {
        return pdname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.pdname
     *
     * @param pdname the value for patient.pdname
     *
     * @mbg.generated
     */
    public void setPdname(String pdname) {
        this.pdname = pdname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.ppassword
     *
     * @return the value of patient.ppassword
     *
     * @mbg.generated
     */
    public String getPpassword() {
        return ppassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.ppassword
     *
     * @param ppassword the value for patient.ppassword
     *
     * @mbg.generated
     */
    public void setPpassword(String ppassword) {
        this.ppassword = ppassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.psex
     *
     * @return the value of patient.psex
     *
     * @mbg.generated
     */
    public Integer getPsex() {
        return psex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.psex
     *
     * @param psex the value for patient.psex
     *
     * @mbg.generated
     */
    public void setPsex(Integer psex) {
        this.psex = psex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.page
     *
     * @return the value of patient.page
     *
     * @mbg.generated
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.page
     *
     * @param page the value for patient.page
     *
     * @mbg.generated
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.paddress
     *
     * @return the value of patient.paddress
     *
     * @mbg.generated
     */
    public String getPaddress() {
        return paddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.paddress
     *
     * @param paddress the value for patient.paddress
     *
     * @mbg.generated
     */
    public void setPaddress(String paddress) {
        this.paddress = paddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.pphone
     *
     * @return the value of patient.pphone
     *
     * @mbg.generated
     */
    public String getPphone() {
        return pphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.pphone
     *
     * @param pphone the value for patient.pphone
     *
     * @mbg.generated
     */
    public void setPphone(String pphone) {
        this.pphone = pphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.pmoney
     *
     * @return the value of patient.pmoney
     *
     * @mbg.generated
     */
    public String getPmoney() {
        return pmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.pmoney
     *
     * @param pmoney the value for patient.pmoney
     *
     * @mbg.generated
     */
    public void setPmoney(String pmoney) {
        this.pmoney = pmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.isdel
     *
     * @return the value of patient.isdel
     *
     * @mbg.generated
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.isdel
     *
     * @param isdel the value for patient.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}