package cn.benevolence.doctor.model;

import java.util.Date;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.isstop
     *
     * @mbg.generated
     */
    private Boolean isstop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.ltime
     *
     * @mbg.generated
     */
    private Date ltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tri_dept.opid
     *
     * @mbg.generated
     */
    private Integer opid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.id
     *
     * @return the value of tri_dept.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.id
     *
     * @param id the value for tri_dept.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.name
     *
     * @return the value of tri_dept.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.name
     *
     * @param name the value for tri_dept.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.area
     *
     * @return the value of tri_dept.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.area
     *
     * @param area the value for tri_dept.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.phone
     *
     * @return the value of tri_dept.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.phone
     *
     * @param phone the value for tri_dept.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.isstop
     *
     * @return the value of tri_dept.isstop
     *
     * @mbg.generated
     */
    public Boolean getIsstop() {
        return isstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.isstop
     *
     * @param isstop the value for tri_dept.isstop
     *
     * @mbg.generated
     */
    public void setIsstop(Boolean isstop) {
        this.isstop = isstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.isdel
     *
     * @return the value of tri_dept.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.isdel
     *
     * @param isdel the value for tri_dept.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.ltime
     *
     * @return the value of tri_dept.ltime
     *
     * @mbg.generated
     */
    public Date getLtime() {
        return ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.ltime
     *
     * @param ltime the value for tri_dept.ltime
     *
     * @mbg.generated
     */
    public void setLtime(Date ltime) {
        this.ltime = ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.ctime
     *
     * @return the value of tri_dept.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.ctime
     *
     * @param ctime the value for tri_dept.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.description
     *
     * @return the value of tri_dept.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.description
     *
     * @param description the value for tri_dept.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tri_dept.opid
     *
     * @return the value of tri_dept.opid
     *
     * @mbg.generated
     */
    public Integer getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tri_dept.opid
     *
     * @param opid the value for tri_dept.opid
     *
     * @mbg.generated
     */
    public void setOpid(Integer opid) {
        this.opid = opid;
    }
}