package cn.benevolence.doctor.model;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.did
     *
     * @mbg.generated
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.dname
     *
     * @mbg.generated
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.dage
     *
     * @mbg.generated
     */
    private Byte dage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.dsex
     *
     * @mbg.generated
     */
    private Integer dsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.ddid
     *
     * @mbg.generated
     */
    private String ddid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.deducation
     *
     * @mbg.generated
     */
    private String deducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.did
     *
     * @return the value of doctor.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.did
     *
     * @param did the value for doctor.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.dname
     *
     * @return the value of doctor.dname
     *
     * @mbg.generated
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.dname
     *
     * @param dname the value for doctor.dname
     *
     * @mbg.generated
     */
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.dage
     *
     * @return the value of doctor.dage
     *
     * @mbg.generated
     */
    public Byte getDage() {
        return dage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.dage
     *
     * @param dage the value for doctor.dage
     *
     * @mbg.generated
     */
    public void setDage(Byte dage) {
        this.dage = dage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.dsex
     *
     * @return the value of doctor.dsex
     *
     * @mbg.generated
     */
    public Integer getDsex() {
        return dsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.dsex
     *
     * @param dsex the value for doctor.dsex
     *
     * @mbg.generated
     */
    public void setDsex(Integer dsex) {
        this.dsex = dsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.ddid
     *
     * @return the value of doctor.ddid
     *
     * @mbg.generated
     */
    public String getDdid() {
        return ddid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.ddid
     *
     * @param ddid the value for doctor.ddid
     *
     * @mbg.generated
     */
    public void setDdid(String ddid) {
        this.ddid = ddid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.position
     *
     * @return the value of doctor.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.position
     *
     * @param position the value for doctor.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.deducation
     *
     * @return the value of doctor.deducation
     *
     * @mbg.generated
     */
    public String getDeducation() {
        return deducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.deducation
     *
     * @param deducation the value for doctor.deducation
     *
     * @mbg.generated
     */
    public void setDeducation(String deducation) {
        this.deducation = deducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.isdel
     *
     * @return the value of doctor.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.isdel
     *
     * @param isdel the value for doctor.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }
}