package cn.benevolence.doctor.model;

import java.util.Date;

public class Scheduling {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_scheduling.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_scheduling.docid
     *
     * @mbg.generated
     */
    private Integer docid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_scheduling.sn
     *
     * @mbg.generated
     */
    private Integer sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_scheduling.climit
     *
     * @mbg.generated
     */
    private Integer climit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_scheduling.sdate
     *
     * @mbg.generated
     */
    private Date sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_scheduling.backgroundColor
     *
     * @mbg.generated
     */
    private String backgroundcolor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_scheduling.id
     *
     * @return the value of doc_scheduling.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_scheduling.id
     *
     * @param id the value for doc_scheduling.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_scheduling.docid
     *
     * @return the value of doc_scheduling.docid
     *
     * @mbg.generated
     */
    public Integer getDocid() {
        return docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_scheduling.docid
     *
     * @param docid the value for doc_scheduling.docid
     *
     * @mbg.generated
     */
    public void setDocid(Integer docid) {
        this.docid = docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_scheduling.sn
     *
     * @return the value of doc_scheduling.sn
     *
     * @mbg.generated
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_scheduling.sn
     *
     * @param sn the value for doc_scheduling.sn
     *
     * @mbg.generated
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_scheduling.climit
     *
     * @return the value of doc_scheduling.climit
     *
     * @mbg.generated
     */
    public Integer getClimit() {
        return climit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_scheduling.climit
     *
     * @param climit the value for doc_scheduling.climit
     *
     * @mbg.generated
     */
    public void setClimit(Integer climit) {
        this.climit = climit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_scheduling.sdate
     *
     * @return the value of doc_scheduling.sdate
     *
     * @mbg.generated
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_scheduling.sdate
     *
     * @param sdate the value for doc_scheduling.sdate
     *
     * @mbg.generated
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_scheduling.backgroundColor
     *
     * @return the value of doc_scheduling.backgroundColor
     *
     * @mbg.generated
     */
    public String getBackgroundcolor() {
        return backgroundcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_scheduling.backgroundColor
     *
     * @param backgroundcolor the value for doc_scheduling.backgroundColor
     *
     * @mbg.generated
     */
    public void setBackgroundcolor(String backgroundcolor) {
        this.backgroundcolor = backgroundcolor;
    }
}