package cn.benevolence.make.mapper;

import cn.benevolence.make.model.VRegistration;
import cn.benevolence.make.model.VRegistrationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface VRegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_registration
     *
     * @mbg.generated
     */
    long countByExample(VRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_registration
     *
     * @mbg.generated
     */
    int deleteByExample(VRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_registration
     *
     * @mbg.generated
     */
    int insert(VRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_registration
     *
     * @mbg.generated
     */
    int insertSelective(VRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_registration
     *
     * @mbg.generated
     */
    List<VRegistration> selectByExample(VRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_registration
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VRegistration record, @Param("example") VRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_registration
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VRegistration record, @Param("example") VRegistrationExample example);
}