package cn.benevolence.history.model;

public class History {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.did
     *
     * @mbg.generated
     */
    private String did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hdiagnose
     *
     * @mbg.generated
     */
    private String hdiagnose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hsymptom
     *
     * @mbg.generated
     */
    private String hsymptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hprescription
     *
     * @mbg.generated
     */
    private String hprescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.isdel
     *
     * @mbg.generated
     */
    private Integer isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.id
     *
     * @return the value of history.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.id
     *
     * @param id the value for history.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.did
     *
     * @return the value of history.did
     *
     * @mbg.generated
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.did
     *
     * @param did the value for history.did
     *
     * @mbg.generated
     */
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.pid
     *
     * @return the value of history.pid
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.pid
     *
     * @param pid the value for history.pid
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hdiagnose
     *
     * @return the value of history.hdiagnose
     *
     * @mbg.generated
     */
    public String getHdiagnose() {
        return hdiagnose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hdiagnose
     *
     * @param hdiagnose the value for history.hdiagnose
     *
     * @mbg.generated
     */
    public void setHdiagnose(String hdiagnose) {
        this.hdiagnose = hdiagnose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hsymptom
     *
     * @return the value of history.hsymptom
     *
     * @mbg.generated
     */
    public String getHsymptom() {
        return hsymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hsymptom
     *
     * @param hsymptom the value for history.hsymptom
     *
     * @mbg.generated
     */
    public void setHsymptom(String hsymptom) {
        this.hsymptom = hsymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hprescription
     *
     * @return the value of history.hprescription
     *
     * @mbg.generated
     */
    public String getHprescription() {
        return hprescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hprescription
     *
     * @param hprescription the value for history.hprescription
     *
     * @mbg.generated
     */
    public void setHprescription(String hprescription) {
        this.hprescription = hprescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.isdel
     *
     * @return the value of history.isdel
     *
     * @mbg.generated
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.isdel
     *
     * @param isdel the value for history.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}