package cn.benevolence.make.model;

public class Information {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.doctorid
     *
     * @mbg.generated
     */
    private Integer doctorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.patientid
     *
     * @mbg.generated
     */
    private Integer patientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.id
     *
     * @return the value of information.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.id
     *
     * @param id the value for information.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.doctorid
     *
     * @return the value of information.doctorid
     *
     * @mbg.generated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.doctorid
     *
     * @param doctorid the value for information.doctorid
     *
     * @mbg.generated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.patientid
     *
     * @return the value of information.patientid
     *
     * @mbg.generated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.patientid
     *
     * @param patientid the value for information.patientid
     *
     * @mbg.generated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.date
     *
     * @return the value of information.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.date
     *
     * @param date the value for information.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.content
     *
     * @return the value of information.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.content
     *
     * @param content the value for information.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.isdel
     *
     * @return the value of information.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.isdel
     *
     * @param isdel the value for information.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }
}