package cn.benevolence.make.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Registration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.patientid
     *
     * @mbg.generated
     */
    private Integer patientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.deptid
     *
     * @mbg.generated
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.doctorid
     *
     * @mbg.generated
     */
    private Integer doctorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.resdate
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    private Date resdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.cdate
     *
     * @mbg.generated
     */

    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.urgent
     *
     * @mbg.generated
     */
    private Boolean urgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_registration.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.id
     *
     * @return the value of make_registration.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.id
     *
     * @param id the value for make_registration.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.patientid
     *
     * @return the value of make_registration.patientid
     *
     * @mbg.generated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.patientid
     *
     * @param patientid the value for make_registration.patientid
     *
     * @mbg.generated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.deptid
     *
     * @return the value of make_registration.deptid
     *
     * @mbg.generated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.deptid
     *
     * @param deptid the value for make_registration.deptid
     *
     * @mbg.generated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.doctorid
     *
     * @return the value of make_registration.doctorid
     *
     * @mbg.generated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.doctorid
     *
     * @param doctorid the value for make_registration.doctorid
     *
     * @mbg.generated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.number
     *
     * @return the value of make_registration.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.number
     *
     * @param number the value for make_registration.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.resdate
     *
     * @return the value of make_registration.resdate
     *
     * @mbg.generated
     */
    public Date getResdate() {
        return resdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.resdate
     *
     * @param resdate the value for make_registration.resdate
     *
     * @mbg.generated
     */
    public void setResdate(Date resdate) {
        this.resdate = resdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.cdate
     *
     * @return the value of make_registration.cdate
     *
     * @mbg.generated
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.cdate
     *
     * @param cdate the value for make_registration.cdate
     *
     * @mbg.generated
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.isdel
     *
     * @return the value of make_registration.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.isdel
     *
     * @param isdel the value for make_registration.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.urgent
     *
     * @return the value of make_registration.urgent
     *
     * @mbg.generated
     */
    public Boolean getUrgent() {
        return urgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.urgent
     *
     * @param urgent the value for make_registration.urgent
     *
     * @mbg.generated
     */
    public void setUrgent(Boolean urgent) {
        this.urgent = urgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.status
     *
     * @return the value of make_registration.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.status
     *
     * @param status the value for make_registration.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_registration.uid
     *
     * @return the value of make_registration.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_registration.uid
     *
     * @param uid the value for make_registration.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}