package cn.benevolence.doctor.mapper;

import cn.benevolence.doctor.model.Scheduling;
import cn.benevolence.doctor.model.SchedulingExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SchedulingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    long countByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int deleteByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int insert(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int insertSelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    List<Scheduling> selectByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    Scheduling selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Scheduling record, @Param("example") SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Scheduling record, @Param("example") SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_scheduling
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Scheduling record);
}